// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beibpjlcoriuebctohcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaWJwamxjb3JpdWViY3RvaGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDg3NDcsImV4cCI6MjA3MTAyNDc0N30.KJ3VQN-HQ_Mk92Macxd4YKtg4QyN5nkrzkdOnFUAUYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});